services:
  frame-up-order-app:
    environment:
        Settings__RabbitMQ__ConnectionString: amqp://guest:guest@localhost:5672
        Settings__PostgreSQL__ConnectionString: Host=frame-up-db;Port=5432;Database=OrderService;Username=postgres;Password=postgres
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_HTTP_PORTS: 8080
        LogBee.OrganizationId": ${LogBee_OrganizationId}
        LogBee.ApplicationId": ${LogBee_ApplicationId}
        LogBee.ApiUrl": ${LogBee_ApiUrl}
        
  frame-up-db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres