on: [ push ]
jobs:
  build-and-test:
    uses: Team-One-Pos-Tech/FrameUp.SharedWorkFlows/.github/workflows/build.yml@main
    with:
      solution-name: "FrameUp.OrderService.sln"
      api-project-name: "FrameUp.OrderService.Api"
      sonar-project-key: "Team-One-Pos-Tech_FrameUp.OrderService"
    secrets:
      sonar-token: ${{secrets.SONAR_TOKEN}}
  
  docker-setup:
    needs: build-and-test
    uses: Team-One-Pos-Tech/FrameUp.SharedWorkFlows/.github/workflows/dockerize.yml@main
    with:
      image-name: "team-one-pos-tech/frameup-order-service"
      api-entrypoint-binary: "FrameUp.OrderService.Api.dll"